services:
  todo:
    image: todo_lab_vs
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://todo-postgresql:5432/todo
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://todo-postgresql:5432/todo
      - JHIPSTER_SLEEP=30
    ports:
      - '8080:8080'
  todo-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
